CREATE TABLE IF NOT EXISTS `#__tst_jglist_static_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `#__tst_jglist_static_category` (`id`, `category`) VALUES
(1, 'Accounting'),
(2, 'Administrative'),
(3, 'Automotive'),
(4, 'Banking'),
(5, 'Biotech'),
(6, 'Business Development'),
(7, 'Business Opportunity'),
(8, 'Clerical'),
(9, 'Construction'),
(10, 'Consultant'),
(11, 'Customer Service'),
(12, 'Design'),
(13, 'Distribution'),
(14, 'Education'),
(15, 'Engineering'),
(16, 'Facilities'),
(17, 'Finance'),
(18, 'Franchise'),
(19, 'General Business'),
(20, 'General Labor'),
(21, 'Government'),
(22, 'Grocery'),
(23, 'Green Jobs'),
(24, 'Health Care'),
(25, 'Hospitality'),
(26, 'Human Resources'),
(27, 'Information Technology'),
(28, 'Maintenance'),
(29, 'Insurance'),
(30, 'Inventory'),
(31, 'Legal'),
(32, 'Legal Administrative'),
(33, 'Logistics'),
(34, 'Manufacturing'),
(35, 'Marketing'),
(36, 'Journalism'),
(37, 'Nonprofit'),
(38, 'Nurse'),
(39, 'Other'),
(40, 'Pharmaceutical'),
(41, 'Professional Services'),
(42, 'Purchasing'),
(43, 'Quality Control'),
(44, 'Real Estate'),
(45, 'Research'),
(46, 'Restaurant'),
(47, 'Retail'),
(48, 'Sales'),
(49, 'Science'),
(50, 'Skilled Labor'),
(51, 'Social Services'),
(52, 'Strategy'),
(53, 'Supply Chain'),
(54, 'Telecommunications'),
(55, 'Training'),
(56, 'Transportation'),
(57, 'Veterinary Services'),
(58, 'Warehouse');
